services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    user: root
    env_file:
      - .env
    ports:
      - "3000:3000"
    extra_hosts:
      - host.docker.internal:host-gateway
    volumes:
      - ./config:/app/config
      - ./config/images:/app/public/images
      - /var/run/docker.sock:/var/run/docker.sock
      - ${EXTERNAL_STORAGE}:/mnt/storage:ro
    restart: unless-stopped
    networks:
      - proxy

networks:
  proxy:
    external: true